### ISSUE TITLE
Add support for Linux.

### ISSUE THREAD

**Issue by Badrpas** [Badrpas/Fly-simulator#4]
In order to keep our position as one of the top projects we have to be open-minded and support as many platforms as legally and logically possible and/or reasonable.

**Comment by pavart** [comment]
Sounds like a good idea. 
Do you have a high-level plan what we need to do to add Linux support?

**Comment by Badrpas** [comment]
Not at the moment. Will add later.

Mentioning @BondarenkoArtur as Linux expert in that matter for more input.

**Comment by BondarenkoArtur** [comment]
One of the things that we need to do is to change our build system to something cross-platform.
For example CMake #9

**Comment by BondarenkoArtur** [comment]
It seems that project is works pretty well on Linux now after fixes #14 and #11.  
The only thing that is needed is probably more detailed explanation in a README about how to build project on different systems, but I think it's not related to this issue, so this one might be closed.
WDYT @Badrpas  ?

**Comment by Badrpas** [comment]
Yes. The goal is met and it's better to keep issues neat and discrete without excess work overlap.
Such things like list of required libraries and supported tools should take different place since there is little or no dependency based on platform.

Created #18 to keep track for it.

Closing this one.
