### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by Badrpas** [Badrpas/Fly-simulator#5]
It's a shame this marvelous gem doesn't have such buzz words as CI/CD in description to it.

It's time to change things to good!

Need to decide on CI platform and implement pipeline into PR flow.

**Comment by pavart** [comment]
We can take [Travis](https://travis-ci.org):
- Free for open source
- Easy to configure
- Good integration with GitHub
- Have nice badges about build status
- I have a little experience working with it
